application: rigmarolesoup
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /admin/?
  script: main.app
  login: admin

- url: /blog/list/?
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: markupsafe
  version: latest

