application: rigmablog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /txt
  static_dir: static/txt

- url: /admin/?.*?
  script: admin.app
  login: admin
 
- url: /blob/.*
  script: blob.app
  login: admin

- url: /serve/.*
  script: blob.app

- url: .*
  script: blog.app

libraries:
- name: markupsafe
  version: latest

builtins:
- remote_api: on
